---
default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: assets/*
      - id: debug-statements
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.19.0
    hooks:
      - id: markdownlint
        language_version: system

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        pass_filenames: false
        args: [".", "--exclude", "migrations/*",]
